# -*- coding: utf-8 -*-
"""EDA_RecommendationDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFEqyKF4-ev4Hldg59RrxkAtQvVOoeg3

**EDA Process for Recommendation System**

* Dataset used: Instacart Market Basket Analysis Dataset
* Link: https://www.kaggle.com/datasets/psparks/instacart-market-basket-analysis
"""

#Import libraries
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix
from sklearn.metrics.pairwise import cosine_similarity
import joblib
import os

#Connect to Kaggle APIs

#Install Kaggle library
!pip install -q kaggle

# Upload kaggle.json APIs key file from Google Drive
from google.colab import drive
drive.mount('/content/drive')

source_path = '/content/drive/MyDrive/kaggle_credentials/kaggle.json'
destination_dir = '/root/.kaggle'
destination_path = f'{destination_dir}/kaggle.json'

# Create folder to place the Kaggle APIs key json file
os.makedirs(destination_dir, exist_ok=True)
!cp "{source_path}" "{destination_path}"

#Set permission only owner can read and write
!chmod 600 "{destination_path}"

# Download the dataset
!kaggle datasets download -d psparks/instacart-market-basket-analysis

# Unzip the dataset file
!unzip -q instacart-market-basket-analysis.zip -d data/

# Define snack aisle IDs
# Filter the data to pick only the products that relates with the eccommerce website,
# The filteration will be done based on the aisle_ids column from aisle dataset
SNACK_AISLE_IDS = {3, 4, 23, 45, 46, 48, 50, 57, 64, 77, 78, 88, 98, 99, 103, 107, 115, 117, 121, 125}

# Load products file and filter it based on snack aisles
print("\nLoading products...")
products = pd.read_csv('data/products.csv')
snack_products = products[products['aisle_id'].isin(SNACK_AISLE_IDS)]
snack_product_ids = set(snack_products['product_id'])
print(f"Snack products: {len(snack_product_ids)}")

# Load order_products file and filter it based on snack aisles
# The order_products will be loaded in chunks to save memory and will keep only snack items

print("\nLoading order_products (chunked)...")
prior_path = 'data/order_products__prior.csv'
chunk_size = 500000

snack_order_items = []
for i, chunk in enumerate(pd.read_csv(prior_path, chunksize=chunk_size)):
    filtered = chunk[chunk['product_id'].isin(snack_product_ids)]
    snack_order_items.append(filtered)
    if (i+1) % 5 == 0:
        print(f"   Processed {i+1} chunks...")
order_products_snack = pd.concat(snack_order_items, ignore_index=True)
print(f"Snack order items: {len(order_products_snack):,}")

# Keep only orders with at least 2 snack items
# Since we want to find the correlation between snack items,
# we will only consider the orders that have at least 2 snack products
# Any order without snack product or only one snack product will be removed
print("\nFiltering orders with ≥2 snack items...")
item_counts = order_products_snack.groupby('order_id').size().reset_index(name='snack_count')
valid_orders = item_counts[item_counts['snack_count'] >= 2]['order_id']
order_products_snack = order_products_snack[order_products_snack['order_id'].isin(valid_orders)]
print(f"After filtering: {len(order_products_snack):,} order items")

# Load orders file and filter the order that match with order_products_snack id
# Join orders file with order_products_snack. Merch using order_id and attach user_id
print("\nLoading orders...")
orders = pd.read_csv('data/orders.csv')
orders_snack = orders[orders['order_id'].isin(order_products_snack['order_id'].unique())]
order_products_with_user = order_products_snack.merge(
    orders_snack[['order_id', 'user_id']], on='order_id', how='left'
)

# User-product interactions Table
# Aggregate user-product purchases,
# Group by user and product
# We want to see the interaction between user and product.
# Cluster all rows where the same user bought the same product
# and count how many time a user buy a particular product
user_product = order_products_with_user.groupby(['user_id', 'product_id']).size().reset_index(name='purchase_count')
print(f"Unique user-product pairs: {len(user_product):,}")

# Save cleaned user-product interaction table
user_product.to_csv('data/cleaned_user_product.csv', index=False)
print("Saved cleaned user-product interactions to 'data/cleaned_user_product.csv'")

# Save snack product names table
snack_product_df = pd.DataFrame({
    'product_id': list(snack_product_names.keys()),
    'product_name': list(snack_product_names.values())
})
snack_product_df.to_csv('data/snack_product_names.csv', index=False)
print("Saved snack product names to 'data/snack_product_names.csv'")