# -*- coding: utf-8 -*-
"""[EDITED] 01_EDA_and_Preprocessing_RecommendationSys.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKV7-Ju5Sp8Rbh1UXNvIn1K1wXrEVxWy

**Data Preprocessing & EDA Process for Recommendation System**

* Dataset used: Instacart Market Basket Analysis Dataset
* Link: https://www.kaggle.com/datasets/psparks/instacart-market-basket-analysis
"""

#Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

#Connect to Kaggle APIs

#Install Kaggle library
!pip install -q kaggle

# Upload kaggle.json APIs key file from Google Drive
from google.colab import drive
drive.mount('/content/drive')

source_path = '/content/drive/MyDrive/kaggle_credentials/kaggle.json'
destination_dir = '/root/.kaggle'
destination_path = f'{destination_dir}/kaggle.json'

# Create folder to place the Kaggle APIs key json file
os.makedirs(destination_dir, exist_ok=True)
!cp "{source_path}" "{destination_path}"

#Set permission only owner can read and write
!chmod 600 "{destination_path}"

# Download the dataset
!kaggle datasets download -d psparks/instacart-market-basket-analysis

# Unzip the dataset file
!unzip -q instacart-market-basket-analysis.zip -d data/

# Create directories
os.makedirs('data', exist_ok=True)
os.makedirs('plots', exist_ok=True)

# Set style for better visuals
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

"""# EDA on Raw Data"""

print("\n=== Initial EDA on Raw Data ===")

# Load data

raw_orders = pd.read_csv(f"data/orders.csv")
raw_products = pd.read_csv(f"data/products.csv")
raw_aisles = pd.read_csv(f"data/aisles.csv")
raw_departments = pd.read_csv(f"data/departments.csv")
raw_order_products_prior = pd.read_csv(f"data/order_products__prior.csv")
raw_order_products_train = pd.read_csv(f"data/order_products__train.csv")

# Dataset overview
print("\n--- Dataset Overview ---")
print(f"Orders: {raw_orders.shape}")
print(f"Products: {raw_products.shape}")
print(f"Aisles: {raw_aisles.shape}")
print(f"Departments: {raw_departments.shape}")
print(f"Order_products_prior: {raw_order_products_prior.shape}")
print(f"Order_products_train: {raw_order_products_train.shape}")

# Check missing values
print("\n--- Missing Values ---")
print(f"Orders missing: {raw_orders.isnull().sum().sum()}")
print(f"Products missing: {raw_products.isnull().sum().sum()}")
print(f"Aisles missing: {raw_aisles.isnull().sum().sum()}")
print(f"Order_products_prior missing: {raw_order_products_prior.isnull().sum().sum()}")
print(f"Order_products_train missing: {raw_order_products_train.isnull().sum().sum()}")

# Dataset Details
print("\n--- Orders Dataset Information ---\n")
print(f"{raw_orders.info()}")
print("\n--- Products Dataset Information ---\n")
print(f"{raw_products.info()}")
print("\n--- Aisles Dataset Information ---\n")
print(f"{raw_aisles.info()}")
print("\n--- Order_products_prior Dataset Information ---\n")
print(f"{raw_order_products_prior.info()}")
print("\n--- Order_products_train Dataset Information ---\n")
print(f"{raw_order_products_train.info()}")

# Orders analysis
print("\n--- Order Patterns ---")
print(f"Unique users: {raw_orders['user_id'].nunique():,}")
print(f"Total orders: {len(raw_orders):,}")
print(f"Avg orders per user: {len(raw_orders) / raw_orders['user_id'].nunique():.2f}")

# Reorder rate analysis
reorder_rate = raw_order_products_prior['reordered'].mean()
print(f"\n--- Reorder Behavior ---")
print(f"Overall reorder rate: {reorder_rate:.2%}")
print(f"Products with highest reorder rates will become recommendations")

# Days between orders
print("\n--- Days Between Orders ---")
print(raw_orders['days_since_prior_order'].describe())

# Hour distribution
plt.figure()
raw_orders['order_hour_of_day'].hist(bins=24)
plt.title('Orders by Hour of Day')
plt.xlabel('Hour (0-23)')
plt.ylabel('Number of Orders')
plt.savefig('plots/overall_order_hours_distribution.png')
print("Saved: plots/overall_order_hours_distribution.png")

# Top products
product_counts = raw_order_products_prior.groupby('product_id').size().reset_index(name='product_sold_count')
product_counts = product_counts.sort_values('product_sold_count', ascending=False).head(20)
products_with_names = product_counts.reset_index().merge(raw_products, on='product_id')
print("\n--- Top 10 Products ---")
print(products_with_names[['product_name', 'product_sold_count']].head(10))

# Plot the top products
plt.figure(figsize=(10,6))
sns.barplot(data=products_with_names, x='product_sold_count', y='product_name',  hue='product_name', palette='light:yellow', legend=False)
plt.title('Top 10 Products')
plt.xlabel('Total Product Sold')
plt.ylabel('Product Name')
plt.tight_layout()
plt.savefig('plots/overall_top_products_distribution.png')
print("Saved plot: plots/overall_top_products_distribution.png")

"""# Data Preprocessing & Feature Engineering

"""

print("\n=== Cleaning & preparing data for training ===")
# Load aisle file
aisles = pd.read_csv('data/aisles.csv')

print("\n List of Aisles Name\n")

with pd.option_context('display.max_rows', None,
                       'display.max_columns', None
                       ):
    print(aisles)

# Define snack aisle IDs
# Filter the data to pick only the products that suitable and relates with the snack eccommerce website,
# The filteration will be done based on the aisle_ids column from aisle dataset
SNACK_AISLE_IDS = {3, 4, 23, 45, 46, 48, 50, 57, 64, 77, 78, 88, 98, 99, 103, 107, 115, 117, 121, 125}

# Add weight according to recent order.
# To keep up with the ever-changing trend so that the recommendation always according to the latest trend
# Set how fast the influence drops
DECAY_HALF_LIFE = 14 #days

# Load products file and filter it based on snack aisles
print("\nLoading products...")
products = pd.read_csv('data/products.csv')
snack_products = products[products['aisle_id'].isin(SNACK_AISLE_IDS)]
snack_product_ids = set(snack_products['product_id'])
print(f"Snack products: {len(snack_product_ids)}")

# Load order_products file and filter it based on snack aisles
# The order_products will be loaded in chunks to save memory and will keep only snack items

print("\nLoading order_products (chunked)...")
prior_path = 'data/order_products__prior.csv'
chunk_size = 500000

snack_order_items = []
for i, chunk in enumerate(pd.read_csv(prior_path, chunksize=chunk_size)):
    filtered = chunk[chunk['product_id'].isin(snack_product_ids)]
    snack_order_items.append(filtered)
    if (i+1) % 5 == 0:
        print(f"   Processed {i+1} chunks...")
order_products_snack = pd.concat(snack_order_items, ignore_index=True)
print(f"Snack order items: {len(order_products_snack):,}")

# Keep only orders with at least 2 snack items
# Since we want to find the correlation between snack items,
# we will only consider the orders that have at least 2 snack products
# Any order without snack product or only one snack product will be removed
print("\nFiltering orders with ≥2 snack items...")
item_counts = order_products_snack.groupby('order_id').size().reset_index(name='snack_count')
valid_orders = item_counts[item_counts['snack_count'] >= 2]['order_id']
order_products_snack = order_products_snack[order_products_snack['order_id'].isin(valid_orders)]
print(f"After filtering: {len(order_products_snack):,} order items")

# Load orders file and filter the order that match with order_products_snack id
# Join orders file with order_products_snack. Merch using order_id and attach user_id
print("\nLoading orders...")
orders = pd.read_csv('data/orders.csv')
orders_snack = orders[orders['order_id'].isin(order_products_snack['order_id'].unique())]
order_products_with_user = order_products_snack.merge(
    orders_snack[['order_id', 'user_id', 'days_since_prior_order']], on='order_id', how='left'
)

# Compute recency weight for each order item
# Exponential decay: weight = exp(-days / half_life)
# For first order (days_since_prior_order is NaN), assign weight= 1.0

order_products_with_user['days_since'] = order_products_with_user['days_since_prior_order'].fillna(0)
order_products_with_user['weight'] = np.exp(-order_products_with_user['days_since'] / DECAY_HALF_LIFE)

print(f"Weight stats: min={order_products_with_user['weight'].min():.3f}, "
      f"max={order_products_with_user['weight'].max():.3f}, "
      f"mean={order_products_with_user['weight'].mean():.3f}")

# User-product interactions Table
# Aggregate user-product by summing weight,
# Group by user and product

user_product_weighted = order_products_with_user.groupby(
    ['user_id', 'product_id']
)['weight'].sum().reset_index(name='purchase_weight')
print(f"User-product weighted pairs: {len(user_product_weighted):,}")

# Save cleaned user-product interaction table
user_product_weighted.to_csv('data/cleaned_weighted_user_product.csv', index=False)
print("Saved cleaned user-product interactions to 'data/cleaned_weighted_user_product.csv'")

# Save snack product names table
snack_product_names = snack_products[['product_id', 'product_name']].set_index('product_id').to_dict()['product_name']
snack_product_df = pd.DataFrame({
    'product_id': list(snack_product_names.keys()),
    'product_name': list(snack_product_names.values())
})
snack_product_df.to_csv('data/snack_product_names.csv', index=False)
print("Saved snack product names to 'data/snack_product_names.csv'")

"""# EDA on Preprocessed Data"""

print("\n=== EDA on Snack Product Data ===")

# Top 10 Snack Aisles with Most Products
print("\n--- Snack Aisle Distribution ---")

# Count products per aisle_id in snack_products
aisle_counts = snack_products['aisle_id'].value_counts().head(10).reset_index()
aisle_counts.columns = ['aisle_id', 'product_count']

# Merge with aisles to get aisle names
aisle_counts = aisle_counts.merge(aisles[['aisle_id', 'aisle']], on='aisle_id', how='left')

print("Top 10 Snack Aisles by Product Count:")
for _, row in aisle_counts.iterrows():
    print(f"  {row['aisle']}: {row['product_count']} products")

# Plot with aisle names
plt.figure(figsize=(10,6))
sns.barplot(data=aisle_counts, x='product_count', y='aisle',  hue='aisle', palette='pink', legend=False)
plt.title('Top 10 Snack Aisles (Number of Products)')
plt.xlabel('Product Count')
plt.ylabel('Aisle')
plt.tight_layout()
plt.savefig('plots/top_10_snack_aisle_distribution.png')
print("Saved plot: plots/top_10_snack_aisle_distribution.png")

# Most Popular Snack Combinations
# Product pair that most frequently bought together in the same order

print("\n--- Most Frequent Product Pairs ---")

# Create a dictionary: order_id -> list of product_ids in that order
order_to_products = order_products_snack.groupby('order_id')['product_id'].apply(list).to_dict()

# Count co-occurrences (only pairs, not triplets)
from collections import Counter
pair_counter = Counter()

for products in order_to_products.values():
    # Only consider orders with at least 2 products
    if len(products) >= 2:
        # Sort to avoid (A,B) vs (B,A)
        products_sorted = sorted(products)
        for i in range(len(products_sorted)):
            for j in range(i+1, len(products_sorted)):
                pair_counter[(products_sorted[i], products_sorted[j])] += 1

# Get top 10 most frequent pairs
top_pairs = pair_counter.most_common(10)

# Map product IDs to names
product_name_dict = snack_products.set_index('product_id')['product_name'].to_dict()
print("Top 10 most frequently co-purchased snack pairs:")
for (p1, p2), count in top_pairs:
    name1 = product_name_dict.get(p1, str(p1))
    name2 = product_name_dict.get(p2, str(p2))
    print(f"  {name1} + {name2}: appears in {count} orders")

# Bar plot of top pairs

pair_labels = [f"{product_name_dict.get(p1, str(p1))[:20]}\n+\n{product_name_dict.get(p2, str(p2))[:20]}" for (p1,p2),_ in top_pairs]
pair_counts = [count for _,count in top_pairs]

plt.figure(figsize=(12,6))
sns.barplot(x=pair_counts, y=pair_labels, hue=pair_labels, palette='crest')
plt.title('Top 10 Most Frequently Co‑purchased Snack Pairs')
plt.xlabel('Number of Orders')
plt.tight_layout()
plt.savefig('plots/top_snack_pairs.png')
print("Saved plot: plots/top_snack_pairs.png")

# Distribution of Snack Items per Order

print("\n--- Snack Items per Order ---")
items_per_order = order_products_snack.groupby('order_id').size()
print(f"Mean items per order: {items_per_order.mean():.2f}")
print(f"Median items per order: {items_per_order.median():.0f}")
print(f"Max items per order: {items_per_order.max()}")

plt.figure()
items_per_order.hist(bins=30, edgecolor='black')
plt.title('Number of Snack Items per Order (≥2 items)')
plt.xlabel('Snack Items')
plt.ylabel('Number of Orders')
plt.tight_layout()
plt.savefig('plots/snack_items_per_order.png')
print("Saved plot: plots/snack_items_per_order.png")

# Recency Weight Distribution

print("\n--- Recency Weight Distribution ---")
print(f"Weight stats: min={order_products_with_user['weight'].min():.3f}, "
      f"max={order_products_with_user['weight'].max():.3f}, "
      f"mean={order_products_with_user['weight'].mean():.3f}")

plt.figure()
plt.hist(order_products_with_user['weight'], bins=50, edgecolor='black', alpha=0.7)
plt.title('Distribution of Recency Weights (Exponential Decay)')
plt.xlabel('Weight')
plt.ylabel('Number of Order Items')
plt.tight_layout()
plt.savefig('plots/recency_weight_distribution.png')
print("Saved plot: plots/recency_weight_distribution.png")

# Most Popular Snack Product
print("\n--- Top 10 Snack Product Names (by Weighted Purchases) ---")

# Aggregate weighted purchases per product
product_weight = user_product_weighted.groupby('product_id')['purchase_weight'].sum().sort_values(ascending=False)

# Get top 10 and map to names
top10 = product_weight.head(10).reset_index()
top10['product_name'] = top10['product_id'].map(product_name_dict)

# Display names and weights
for _, row in top10.iterrows():
    print(f"  {row['product_name']}: {row['purchase_weight']:.2f}")

# Horizontal bar chart
plt.figure(figsize=(10, 6))
sns.barplot(data=top10, y='product_name', x='purchase_weight', hue='product_name', palette='viridis')
plt.title('Top 10 Snack Products by Total Weighted Purchases')
plt.xlabel('Total Weight')
plt.ylabel('')
plt.tight_layout()
plt.savefig('plots/top_snack_products_by_weighted_purchases.png')
print("Saved plot: plots/top_snack_products_by_weighted_purchases.png")

# Final summary

print("\n" + "=" * 60)
print("EDA AND CLEANING COMPLETE")
print("=" * 60)
print(f"Total unique users: {user_product_weighted['user_id'].nunique():,}")
print(f"Total unique snack products: {user_product_weighted['product_id'].nunique():,}")
print(f"Total weighted interactions: {len(user_product_weighted):,}")
print("Plots saved to 'plots/' directory.")